source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/dajiangjun887/FZPodSpecs.git'
use_frameworks!

platform :ios, '11.0'

target 'FZModuleKit_Example' do
  pod 'FZModuleKit', :path => '../'

  target 'FZModuleKit_Tests' do
    inherit! :search_paths
    pod 'FZCommitKit'
    pod 'SnapKit'
  end
end
